//
// Created by Leon on 29.04.2019.
//

#ifndef ASSIGNMENT_18_EXCESS_LEONNEPELIUS_EXCESS_H
#define ASSIGNMENT_18_EXCESS_LEONNEPELIUS_EXCESS_H

void read_textfile();

#endif //ASSIGNMENT_18_EXCESS_LEONNEPELIUS_EXCESS_H
